########### Name of the Dockerfile
name: Build and Push Docker Image to GHCR

########### Creates a type of event listener to execute the below steps when main is pushed or a pull request is opened or updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

########### Defines what will be executed when the event above is activated, this then runs on the latest version of Ubuntu
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    ########### Grants the necessary permissions to the Github Token used in the workflow
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    
    steps:
      ########### Step 1: Checks out or reads the code from the Repository
      - name: Checkout code
        uses: actions/checkout@v2


      ########### Step 2: Logs into the Github Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          # The GitHub username and token are stored as secrets in the repository settings under "Secrets and Variables"
          username: ${{ secrets.GHCR_USERNAME }}  
          password: ${{ secrets.GHCR_TOKEN }} 
          registry: ghcr.io

      ########### Step 3: Builds the Docker Image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/willg08/devops/starwars-api:latest .
    
      ########### Step 4: Pushes the Docker Image
      - name: Push Docker image
        run: |
          docker push ghcr.io/willg08/devops/starwars-api:latest